### ISSUE TITLE
Localization system

### ISSUE THREAD

**Issue by adrianoapj** [hackclub/apply#37]
Hey everyone! My name is Adriano, I am from Brazil and as you may know, Hack Club started to accept applications in Portuguese for something about 2 months ago.

And that's awesome! However, it could be even better if we also managed to translate the questions and every other visible string on the page, and that's why I'm opening this issue!

So I though in 2 possible approaches to fix this problem and here they are:

1 - Fork this project, and host a new separated application, exactly like the one that is in this repo, but changing the hard-coded strings to Portuguese. Then we could open a PR to hackclub/dns to point it to something like br.apply.hackclub.com

2 - Implement a full localization system that would probably use the same approach as #31 to find out the user's language and then use .yml files to store all the strings in different languages.

In both cases, @farreltobias and I can work on it. Also, if you have another idea, let us know!
I'm opening this issue to avoid unnecessary work on any of these solutions above if they are not possible to be executed.

What do you think?

**Comment by sampoder** [comment]
Hey Adriano! This sounds like a great idea! @maxwofford thoughts? 

:D

**Comment by maxwofford** [comment]
Want to loop in @MatthewStanciu. I'm happy to talk on the technical side (& super appreciate the translation support @adrianoapj), but I want to make sure this is inline with what the clubs side wants/needs before I dive in
